class DataBase: pass
class ChatMember: pass
class CallbackQuery: pass
class Chat: pass
class User: pass
class Message: pass
class MenuKeyboardMarkup: pass
class InlineKeyboardMarkup: pass
class InputFile: pass
class ChatActions: pass
class LabeledPrice: pass
class Document: pass
class Audio: pass
class Photo: pass
class Video: pass
class Voice: pass
class Contact: pass
class Location: pass
class InlineKeyboardButton: pass
class InlineKeyboardMarkup: pass
class MenuKeyboardButton: pass
class MenuKeyboardMarkup: pass
class InputMediaAudio: pass
class InputMediaDocument: pass
class InputMediaPhoto: pass
class InputMediaVideo: pass
class InputMediaAnimation: pass