name: Deploy Sphinx Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install sphinx furo sphinx-autoapi sphinx-copybutton sphinx-design sphinx-material

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Create CNAME file
        run: |
          echo "docs.pyrobale.ir" > docs/build/html/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html